title: Yells Switchwire Notes
description: Informations and Troubleshooting
theme: just-the-docs
color_scheme: dark

markdown: kramdown
url: https://yell3d.github.io
baseurl: /Switchwire
logo: "/res/img/yell.png"
favicon_ico: "/res/img/favicon.ico"
callouts:
  warning:
    title: Warning
    color: red
  stop:
    color: red


aux_links:
  "Support me on Ko-Fi":
    - "//ko-fi.com/yell3d"
  "Or directly on paypal":
    - "//paypal.me/MPockrandt"
  "here is my Printables":
    - "//printables.com/@Yell"
