title: Yell's Switchwire Notes
description: Informations and Troubleshooting
theme: just-the-docs
color_scheme: dark

markdown: kramdown
baseurl: /Switchwire
url: https://yell3d.github.io
logo: "/res/img/yell.png"
favicon_ico: "/res/img/favicon.ico"
callouts:
  warning:
    title: Warning
    color: red
  stop:
    color: red


aux_links:
  "Support me on Ko-Fi":
    - "//ko-fi.com/yell3d"
  "Or via on paypal":
    - "//paypal.me/MPockrandt"
  "my Printables":
    - "//printables.com/@Yell"
